# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogeneral',
            name='estatura',
            field=models.CharField(default='', max_length=50),
        ),
    ]
